### ISSUE TITLE
如何运行项目

### ISSUE THREAD

**Issue by tarataro** [uphe/classroomsystem#3]
tomcat已连接
直接运行项目首页出现404（请求的资源不可用）
若运行登录页面，点击登录按钮后出现500 java.lang.NullPointerException的错误
请问如何解决？谢谢！

**Comment by uphe** [comment]
不好意思，最近在忙其他的事情，你那边运行成功了吗（我有朋友用过这个项目是可以的） ---- 回复的原邮件 ***@***.***>发送日期2021年05月27日 12:07 ***@***.***> ***@***.***>主题[uphe/classroomsystem] 如何运行项目 (#3)

tomcat已连接

直接运行项目首页出现404（请求的资源不可用）

若运行登录页面，点击登录按钮后出现500 java.lang.NullPointerException的错误

请问如何解决？谢谢！



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/uphe/classroomsystem/issues/3",

"url": "https://github.com/uphe/classroomsystem/issues/3",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
